version: '3.8'
services:
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - test
  #    volumes:
  #      - './data/redis:/bitnami/redis/data'

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-server
    volumes:
#      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/my.cnf
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql123"
      - "MYSQL_DATABASE=user"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    networks:
      - test

#  canal-server:
#    image: canal/canal-server:v1.1.1
#    container_name: canal-server
#    ports:
#      - "11111:11111"
#    networks:
#      - test
#    volumes:
#      - ./conf/canal/example/:/home/admin/canal-server/conf/example/
#      - ./canal-server-logs/:/home/admin/canal-server/logs/
#    depends_on:
#      - mysql


networks:
  test:
    driver: bridge
